---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: alerts
    notifications.argoproj.io/subscribe.on-sync-failed.slack: alerts
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: alerts
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/devops-terraform-aws/argocd.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp

  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #     allowEmpty: false
  #   syncOptions:
  #     - Validate=true
  #     - CreateNamespace=false
  #     - PrunePropagationPolicy=foreground
  #     - PruneLast=true

  # syncPolicy:
  #   syncOptions:
  #   - CreateNamespace=true

  #   automated:
  #     selfHeal: true
  #     prune: true